[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

build_flags =
    -DMOISTURE_PIN=1
    -DLED_RED_PIN=4
    -DLED_GREEN_PIN=5
    -DSENSOR_POWER_PIN=6
    -DSOLAR_ADC_PIN=0
    -DARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    ; BLE support built into ESP32 Arduino core
